# Generated by Django 4.2.6 on 2023-11-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
